# Generated by Django 4.2.11 on 2024-03-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado'), (4, 'Pendiente'), (5, 'Vencido')], default=1)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('total_sunat', models.IntegerField(default=0)),
                ('date_finish_sunat', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
    ]
