# Generated by Django 4.2.11 on 2024-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
