# Generated by Django 4.2.11 on 2026-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='limit_sunat',
            field=models.IntegerField(default=2000),
        ),
    ]
