# Generated by Django 4.2.11 on 2024-03-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado'), (4, 'Pendiente'), (5, 'Vencido')], default=1)),
                ('document_number', models.CharField(max_length=24, unique=True)),
                ('payload', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'Ruc',
            },
        ),
        migrations.CreateModel(
            name='InteractionSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado'), (4, 'Pendiente'), (5, 'Vencido')], default=1)),
                ('document_number', models.CharField(max_length=24)),
                ('payload', models.JSONField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'Interaction_Sunat',
            },
        ),
    ]
