# Generated by Django 4.2.11 on 2024-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionsunat',
            name='scraping',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
