# Generated by Django 4.2.11 on 2024-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0002_interactionsunat_scraping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado'), (4, 'Pendiente'), (5, 'Vencido')], default=1)),
                ('ruc', models.CharField(max_length=16, unique=True)),
                ('ubigeo', models.CharField(max_length=6, null=True)),
                ('tipo_via', models.CharField(max_length=50, null=True)),
                ('nombre_via', models.CharField(max_length=100, null=True)),
                ('codigo_zona', models.CharField(max_length=10, null=True)),
                ('tipo_zona', models.CharField(max_length=50, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('kilometro', models.CharField(max_length=10, null=True)),
                ('interior', models.CharField(max_length=10, null=True)),
                ('lote', models.CharField(max_length=10, null=True)),
                ('departamento_anexo', models.CharField(max_length=50, null=True)),
                ('manzana', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Direccion_Sunat',
            },
        ),
        migrations.CreateModel(
            name='TempDireccionSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado'), (4, 'Pendiente'), (5, 'Vencido')], default=1)),
                ('ruc', models.CharField(max_length=16, null=True)),
                ('ubigeo', models.CharField(max_length=6, null=True)),
                ('tipo_via', models.CharField(max_length=50, null=True)),
                ('nombre_via', models.CharField(max_length=100, null=True)),
                ('codigo_zona', models.CharField(max_length=10, null=True)),
                ('tipo_zona', models.CharField(max_length=50, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('kilometro', models.CharField(max_length=10, null=True)),
                ('interior', models.CharField(max_length=10, null=True)),
                ('lote', models.CharField(max_length=10, null=True)),
                ('departamento_anexo', models.CharField(max_length=50, null=True)),
                ('manzana', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'temporales"."Temp_Direccion_Sunat',
            },
        ),
    ]
