# Generated by Django 4.2.11 on 2024-03-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0003_direccion_tempdireccionsunat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='updated_at',
        ),
    ]
