# Generated by Django 4.2.11 on 2024-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0004_remove_tempdireccionsunat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='interactionsunat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
