# Generated by Django 4.2.11 on 2024-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0005_alter_direccion_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='codigo_zona',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='departamento_anexo',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='kilometro',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='manzana',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='nombre_via',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='tipo_via',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='tipo_zona',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='codigo_zona',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='departamento_anexo',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='kilometro',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='manzana',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='nombre_via',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='tipo_via',
        ),
        migrations.RemoveField(
            model_name='tempdireccionsunat',
            name='tipo_zona',
        ),
        migrations.AddField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='distrito',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='provincia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tempdireccionsunat',
            name='departamento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tempdireccionsunat',
            name='distrito',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tempdireccionsunat',
            name='provincia',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
