# Generated by Django 4.2.11 on 2024-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0006_remove_direccion_codigo_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ubigeo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tempdireccionsunat',
            name='ubigeo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
